# Generated by Django 6.0.1 on 2026-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image_class', models.CharField(default='gradient-1', help_text='CSS class for the project image block (e.g. gradient-1).', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. React, Node.js, MongoDB).', max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
