# Generated by Django 6.0.1 on 2026-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_alter_portfolio_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_class',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
