# Generated by Django 6.0.1 on 2026-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_remove_project_image_class_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tags',
            new_name='tags1',
        ),
        migrations.AddField(
            model_name='project',
            name='tags2',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. React, Node.js, MongoDB).', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='tags3',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. React, Node.js, MongoDB).', max_length=255),
        ),
    ]
